### ISSUE TITLE
Map multiplicity from seqmeta data to size of node in the tree

### ISSUE THREAD

**Issue by eharkins** [matsengrp/olmsted#11]
` "cft.reconstruction:seqmeta": [{"tripl.csv:data": ["*"]}]`
`multiplicity` and `cluster_multiplicity` both refer to the number of sequences represented by one of the downsampled sequences we choose for ancestral-state/tree reconstruction. However, `multiplicity` only accounts for sequences that are 100% identical to a given examplar/representative sequence. `cluster_multiplicity` on the other hand, also takes into account the sequences on the tree that fall within the clusters we get out of the minadcl pruning step. So the `cluster_multiplicity` numbers will in general be bigger. We want to show one of these two measurements through the size of the node in the tree. Which of the two measurements should be selected in a dropdown (bind select)

**Comment by eharkins** [comment]
In cft web, if a leaf in the FastTree is chosen in the downsampling process, and happens to have an identical sequence to one of the ASR tree's internal nodes, it will show up as a leaf on one of the length  0 branches from said internal node, since it must be included as a leaf by ASR given that it came from a leaf of the FastTree. This leaf on a length 0 branch will then have multiplicity, which is as if the internal node had multiplicity.

There is the question here of how to treat these "internal nodes" with respect to multiplicity. Rather than try to do something clever with the internal nodes having multiplicity, we are in agreement that leaving the internal nodes alone for now while we match the features of cft web regarding the leaves, and then see where we stand later when we decide the behavior we want for the internal nodes.

Part of the reason for this is that Duncan is working on statistics per internal node, and @metasoarous expressed interest in being able to color nodes by these statistics. So continuing to treat internal nodes differently than leaves might mean less UI complexity if it's assumed that we will want internal nodes to be colored by something different than leaf nodes.

**Comment by metasoarous** [comment]
>  ... since it must be included as a leaf by ASR given that it came from a leaf of the FastTree

Really since assumed it was chosen in the downsampling process.

:+1: on everything else

**Comment by metasoarous** [comment]
This is looking promising!

![image](https://user-images.githubusercontent.com/88556/45983745-cca35280-c012-11e8-9b8c-2e2bf12300d7.png)

In my head, I was imagining these circles would be color filled, maybe at 33% opacity so that you can see overlap, and get a better sense for color distribution and sense of area. But the non-filled marks, as used above, are actually better at alleviating the overlap problem, so maybe worth keeping. We will want filled when we get to coloring by timepoint, as we'll want to do little pie charts. But maybe whether marks are filled should be another UI option?

It may be worth trying to align the pie-charts and/or other marks as they are in cftweb. Above, marks are centered on the points. If its possible to offset them by their width, or otherwise specify some more nuanced relationship between how things align, it may be worth experimenting with that to see what we think. If circles are filled, this may make it easier to avoid messy information overlap in the viz. It may be more trouble than its worth though, and inform the questions posed above.

**Comment by metasoarous** [comment]
Oh my! This is fun! Will have to figure out the scales here huh, @eharkins?

![image](https://user-images.githubusercontent.com/88556/45984110-63244380-c014-11e8-847b-2d00dc55f2fd.png)

**Comment by metasoarous** [comment]
Note that a lot of this problem goes away once we have the ability to highlight nodes and/or labels in the viz, as then it'll be a little easier to see what pairs with what. Also, adding some info to the hover tooltip would be helpful.

> We can easily set a range of possible values for the size of these circles. It still will not be a solution to their overlapping, but will not allow the max value to balloon depending on the data.

Can you clarify this? How does this not help the overlap problem? To be clear, I'm okay with some overlap, like in the first snapshot above. The max circle size though should never be bigger than where you can roughly guess the corresponding label to be.

I'm happy with there being an option for the size selection dropdown which is effectively none.

**Comment by eharkins** [comment]
> Can you clarify this? How does this not help the overlap problem? To be clear, I'm okay with some overlap, like in the first snapshot above. 

Sorry that was a slightly pessimistic word choice: Setting a range on the leaf circle size _does_ help the overlap problem, it's just not a perfect solutions since we might still have some overlap (especially if we want to map a broad range of values and see the nuanced difference between them). But as you said, a little bit of overlap is maybe ok. 

> The max circle size though should never be bigger than where you can roughly guess the corresponding label to be.

This seems sort of subjective but we can make a reasonable assumption and just try to make things as obvious as possible for the user.

So this is my takeaway: 
- Set the range max to a reasonable value so that circles are obviously paired with their label
- Add some hover tooltip for getting info about the hovered leaf 
-- Side note: I wonder if we can store the value of the hovered leaf sequence id in a signal and use this to highlight the corresponding alignment since it's all in the same spec
- Add an option for leaf sizes to all be uniform
- What about color and/or opacity - should we leave this for a separate issue re: pie charts?

**Comment by metasoarous** [comment]
I agree with your takeaway. Getting in the weeds...

> it's just not a perfect solution since we might still have some overlap (especially if we want to map a broad range of values and see the nuanced difference between them)

I think what this highlights is that we should add a way to scale the max circle size to expose those differences. But first lets get a sane default to build on so that we can prioritize that in relation to everything else.

> This seems sort of subjective but we can make a reasonable assumption

Seems like a max of around 5-7 labels wide in circumference would do the trick? Though I guess we should figure out what happens with a bunch of multiplicity 1 sequences in that case.

> -- Side note: I wonder if we can store the value of the hovered leaf sequence id in a signal and use this to highlight the corresponding alignment since it's all in the same spec

I think that makes sense.

> What about color and/or opacity - should we leave this for a separate issue re: pie charts?

Yeah, leave this for a separate issue, maybe even separate from the pie charts, since its really about what to do when we aren't doing the pie charts.

**Comment by eharkins** [comment]
@metasoarous check out the latest commit and let me know if it does a decent job of addressing the above concerns. If so, we can close this for now

**Comment by metasoarous** [comment]
Looks good!

Only thing is that we should default to regular multiplicity for seed pruned trees, and probably not even present the cluster multiplicities option, because it isn't defined except for minadcl trees. I'll open this as another issue for now, since otherwise things seem good here.
