### ISSUE TITLE
Remove superfluous space underneath tree-alignment

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#43]
Shouldn't have to scroll past to get to lineage alignment.

**Comment by eharkins** [comment]
To clarify, are you just saying the height of the tree/alignment viz component container should depend on the height scale of the viz itself so that there isn't empty space before the lineage viz? I agree, and a side note that will hopefully go along with this is that the tree/alignment scaling controls should really be at the top of that viz if possible, so that they don't shift around when you change the height scale. I'm not sure if there's a way to do this officially in vega or not, but we can make it happen one way or another.

**Comment by metasoarous** [comment]
Yup; realized I meant "Shouldn't" not "Should". Corrected above now.

**Comment by eharkins** [comment]
> Looks like this is now resolved.

It still looks like making the height scale below a certain number causes this problem. In general it's still not that intuitive to have the control you are using move around while you are using it (referring to the height scale of the tree). Or were you saying that it would be resolved once we do the zoom feature we were discussing in #28

**Comment by metasoarous** [comment]
Ah; I wasn't looking at it zoomed out when I posted.

Do we know why this is happening? Why does it scale the overall height when you increase the scale, but below some threshold not do this? Is there a min-height getting set somewhere?

I'm not 100% sold that controls should be on the top. Maybe open another issue for that if there isn't one already, so we can discuss.

**Comment by eharkins** [comment]
Not sure why it is happening, but it seems like there should be a straightforward answer to this if we do a little investigation. I am happy to do that. Making another issue for where the controls should go.

**Comment by metasoarous** [comment]
@eharkins I have ideas on this; see #28.
