### ISSUE TITLE
Design the method of deselecting clonal family

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#46]
From discussion around #2 with @lauranoges, it was decided that rather than automatically selecting the first clonal family when brush selection updates (which comes with a responsiveness cost to the brush selection), we should perhaps instead just clear the last selected tree to avoid the confusion about its association with the currently selected region.

**Comment by metasoarous** [comment]
Unfortunately, the solution to this issue seems to be an impediment to getting #3 in. Since in general my preference is for us to improve the fundamental value of the visualizations, I think we should scratch the solution to this issue (#46) as written when we get around to #3. Once we've gotten through the rest of the low hanging fruit for v1, we can come back to this issue and see if there's a better way to solve the problem.

For future reference then, the underlying conflict with #3 is that if brush selection clears the clonal family selection from the table, and if the selected clonal family is also somehow highlighted in the viz, you end up with an infinite cycle of state updates and renders when brushing which make the tool nearly useless.

One simple solution here would be to just drop this issue as written, and instead simply add a little "x" at the cornder of the selected clonal family so that it could be unselected.

Ideally though, we'd have a better way for coordinating updates of this cyclical sort with React & Vega. Its possible here that by looking at more advanced features of react, we can be a little more careful about when we render (componentWillRender?), and lean on some more advanced part of the Vega API to update the data passed in without having to rerender. This will be a fun little issue to sort out once we've got the low hanging fruit of v1 banged out.

**Comment by eharkins** [comment]
To clarify, the problem with trying to implement both #3 and this issue together is that, as is said above, a solution to this issue means clearing the selected family from Redux state on brush select. However, in #3 we must subscribe the brushing-viz-component to updates to the selected family in order to display it. The result means when there is a selected family in Redux state, and the user tries to brush, the component re-renders as the selected family is cleared from state (a change has happened that we subscribed to) and it interrupts the brush select, causing brush select to fail in this case.

Also, I think https://reactjs.org/docs/react-component.html#shouldcomponentupdate is the method that does what you are hoping for @metasoarous, which feels similar to customizing the react-redux `connect`.  Either way, we are still not sure of an exact solution, I just wanted to note these details here for later.

**Comment by metasoarous** [comment]
Another thing we might be able to do here is use a selector on the redux store so that once the clonal family is unselected, the selector (for the selectedClonalFamily value) won't trigger downstream changes unless the value has actually. In particular then, as the brush selection moves around, the selector will just see a bunch of undefined values, and won't pass on downstream changes. So then in the clonal families viz component, we can subscribe to the gated selector, rather than whole-hog to the entire store. However, this means that if you already have a clonal family selected when you start brushing, there may be an initial jitter as the first state change from something -> `undefined` comes through. One way around this is to maybe clear the selected clonal family on initial mousedown to the viz? That way, by the time the brush starts moving around and updating the store, the selectedClonalFamily has already been set to `undefined`, and the selector can do its work. This may end up being the cleanest way to do it.

**Comment by eharkins** [comment]
In experimenting yesterday, I experienced the "jitter" you described. Even when the selected family is being cleared on the initial mousedown (which is part of the brush select's list of events that trigger it's handler), this actually causes a re-render and then it doesn't pick back up where it left off tracking your brush selection since your mouse is already down before it renders and it is looking for mousemove events _between_ mousedown and mouseup. Let me know if that doesn't make sense.

**Comment by eharkins** [comment]
@lauradoepker Long story short, we are prioritizing #3 over this issue and keeping this open as it is representative of a larger question of "how do we interact with things and have them update themselves smoothly as we interact in a _continuous_ way and have them update continuously without reloading themselves." This may seem counter to the idea of React but it is a specific version of that problem whose solution just isn't obvious right now, and we are hoping to answer it later on.

**Comment by eharkins** [comment]
#3 is now closed and the solution (which in short is taking advantage of react-vega's ability to update data sources dynamically without re-loading the viz) allows us to deselect the selected family (from the redux state) without causing any undesired side effects in the scatterplot. So now the only question is how we want to deselect selected clonal families. @metasoarous' suggestion is to have it be 'sticky' by default, meaning the family stays selected unless you explicitly deselect it or select another. 

Ways of deselecting could be
* a 'close' or 'x' button somewhere reasonable like next to the family details title
* the ability to actually uncheck the checkboxes
* a redesign of the checkbox concept where clicking either a part of a row or an entire row will toggle the family as selected. We could use cues other than a checkbox like changing the cursor to encourage users to click the rows. 

@lauradoepker any preference?

I am changing the name of the issue to reflect that we have the option to deselect and now it's a design question.

**Comment by lauradoepker** [comment]
All of those options sound great, so it's up to you re: what's easiest or what you prefer.  We definitely need stickiness in that we can't have families that were selected just fall off.  Unless we redo the click/drag/select action to highlight different families entirely.

**Comment by eharkins** [comment]
@metasoarous @lauradoepker should I close this once #84 , #86 are closed and then we will track the more complex selection of multiple families / having a comparison view with #47 and/or create a separate issue for viewing multiple families at once / comparing?

**Comment by metasoarous** [comment]
I defer to @lauradoepker on this. Definitely open up an issue for a comparison view if we don't have one already.

**Comment by eharkins** [comment]
Created #88 for comparison view. If Laura is ok with reselecting / autoselecting new families over explicitly deselecting a family, then I will close this once #86 is resolved since #84 is now closed. Otherwise we can add a method of just deselecting a family so that no tree is visible, but I'm not sure if this has an advantage over just selecting a new one.

**Comment by eharkins** [comment]
Closing this now that #86 and #84 are resolved; our method of deselecting is just selecting anew either manually or by autoselect (see #2)

**Comment by eharkins** [comment]
Closing this now that #86 and #84 are resolved; our method of deselecting is just selecting anew either manually or by autoselect (see #2)
