### ISSUE TITLE
Improve alignment color, readability

### ISSUE THREAD

**Issue by eharkins** [matsengrp/olmsted#48]
Need to make the color coding match the standard for amino acids (as on cft web?), and should use transparent or black or something to set apart the deletion '-' character. Maybe gray for 'X' which comes from having 'N' in the nucleotide sequence

**Comment by lauradoepker** [comment]
I’m not sure CFT has the official colors… I believe I created an issue about AA colors on CFT or CFTweb reps.  There are several color wheels for AAs though one method is most widely used.  Side note: I like your classy “soft” colors, stylistically.

**Comment by metasoarous** [comment]
CFTWeb does have an at least somewhat standard color color scheme (from [IMGT](http://www.imgt.org/IMGTScientificChart/RepresentationRules/colormenu.php)), where each AA has a unique color.

The issue you question is matsengrp/cftweb#10, and if I recall correctly the color scheme you wanted is one where colors are assigned based on AA hydrostatic properties (or some such). This kind of makes sense in CFTWeb, as we also display the AA character itself, so the colors themselves are more secondary in function. However, for this particular viz, since we don't see the AA characters without hovering, I'd advise using the more differentiating color scheme by default, so these details don't get glossed over. I get that to a certain extent some glossing over here may be okay, or even helpful if one is really just interested in seeing where these AA properties are actually changing. But perhaps this should itself be another configuration option so that users could choose?

If you do decide to use the full color scheme from CFTWeb, its here: https://github.com/matsengrp/cftweb/blob/master/cftweb/static/dashboard.css

**Comment by lauradoepker** [comment]
Yeah, you’re right.  Probably best to have a specific color per AA, instead of the duplicates that are in the scheme I recommended.  I’m fine with any color scheme because my brain doesn’t recognize any of the color schemes anyway… I just look at the AA identity and know the properties by memory.

**Comment by eharkins** [comment]
Side note that can probably be tacked on to this issue: in general (ie in the rest of the visualizations as well) we should stick to contrasting / colorblindness-proof color schemes when possible unless there is an standard such as with AA color codes. All of this should be simple to change in vega specs.

**Comment by metasoarous** [comment]
@eharkins Made note of this over in #53.

**Comment by eharkins** [comment]
I've added both the cft colors (which you can turn on by changing a few lines) and another set (which is the current default) that are less vibrant but still unique across 20 AA chars plus gap character '-' and 'X' (which comes from 'N' in the dna sequence I believe). Open to thoughts, @metasoarous and @lauradoepker (when we get a chance to show you). 

I had to add two more colors for '-' and 'X'. Alternatively, we could try to handle this with some other design choice like trying to change the mark style or size for these characters. What do you all think is the best way to distinguish these characters based on their biological meaning?

In terms of colorblindness, it seems pretty difficult to get so many unique colors and still be colorblind friendly.

**Comment by lauradoepker** [comment]
That sounds great.  '-' characters should be transparent so they look like a gap.  'X' characters are usually just for padding at the beginning or end of genes because they don't usually indicate ambiguity, so it doesn't really matter what color 'X's are... grey would be good. @eharkins

**Comment by eharkins** [comment]
@lauradoepker Sounds good. I'm using black for 'X' since grey is already in use by this color scheme. For gaps, does having them transparent make it hard to distinguish from the fact that our default when there is no mutation at a position is to show a transparent square? See below where the top left corner are gaps but the rest of the non-colored areas are not.

![screen shot 2018-10-03 at 10 46 30 am](https://user-images.githubusercontent.com/12140437/46428898-fdae1200-c6f9-11e8-8697-867930cda851.png)

**Comment by lauradoepker** [comment]
Can the '-' be a transparent square with a big black '-' in it?  So it would look like a '-'?

**Comment by eharkins** [comment]
I believe that's a possibility. I'll give it a shot and let you know!

**Comment by metasoarous** [comment]
Black is fine, but I'm wondering if there's a better dark-grey color that would stand out from the rest of the without screaming so loudly.

**Comment by eharkins** [comment]
@lauradoepker how does this look?
![screen shot 2018-10-03 at 2 31 38 pm](https://user-images.githubusercontent.com/12140437/46440728-18dc4a00-c719-11e8-9229-c8d79f127ad9.png)

**Comment by lauradoepker** [comment]
Looks great!  I don't care re: X vs black box.  X sounds reasonable, because then color blocks are only for bonafide AAs.

**Comment by eharkins** [comment]
Alright I'll do Xs unless you were keen on having a specific color for X @metasoarous?

**Comment by metasoarous** [comment]
That looks great! X would be nice I think, if easy enough.

**Comment by eharkins** [comment]
![screen shot 2018-10-03 at 3 18 32 pm](https://user-images.githubusercontent.com/12140437/46442760-9efb8f00-c71f-11e8-9da1-51ac890a8429.png)

**Comment by metasoarous** [comment]
Dope! :shipit:
