### ISSUE TITLE
Add pie charts for timepoint multiplicities

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#56]
There are analogs of `multiplicity` and `cluster_multiplicity` which account for timepoints: `multiplicities` and `cluster_multiplicities`. These plural attributes point to `:` separated lists of multiplicities, ordered per timepoint in the `timepoints` column (also `:` separated). This is a little nonstandard, and would maybe be better as json, but it follows the partis output convention.

We can use vega's arc marcs to create these little pie charts. We can even use `innerRadius` to make these pies hollow in the center, so that they overlap more gracefully. Vega docs:

https://vega.github.io/vega/docs/marks/arc/

Note that this will mean some preprocessing, as here the datum level of the mark is unique combinations of `(minadcl_representative, timepoint)`. So we'll have to "flatten" this information out of the nested `multiplicities` and `cluster_multiplicities` cols.

**Comment by metasoarous** [comment]
See related issue #11.

**Comment by eharkins** [comment]
While the SConstruct in cft doesn't allow us to get timepoint multiplicities yet, after discussing with @metasoarous today, I am going to merge in the branch for this issue, which does most of the work necessary for vega to handle pie charts from timepoint multiplicity data, so that it can stay up to date with master. I'll leave this issue open until we finish ongoing work in cft and are able to create pie charts from actual timepoint multiplicities instead of test data that is currently added by `bin/build_olmsted_data.py` @ 56-pie-charts branch

**Comment by eharkins** [comment]
@lauradoepker and/or @metasoarous do you think we need a key for the pie charts (like on cft web) to show which color corresponds to which timepoint or should we just have the ability to hover on them to get more information?

**Comment by eharkins** [comment]
@lauradoepker there are already pie charts (you can see them with some dummy data that shows the same timepoint multiplicities for all sequences @ http://stoat:3999/). But we can show the same information shown by the pie charts on hovering, which would address issues like you describe: when the pie chart is too small / you are not sure how the colors map to timepoints.

**Comment by metasoarous** [comment]
I think ideally we'll want both the hover and the legend/key. Legend is important for static interpretability, while hover is good for accessing specific numbers, as @lauradoepker suggests.

**Comment by eharkins** [comment]
Update: Chris has added these timepoint multiplicities into the data, but because of the way the [pie transform](https://vega.github.io/vega/docs/transforms/pie/) works, all the leaves need to have timepoint multiplicity values for the charts to work (and not have the effect they have now which is that some are incomplete pies like this
![Screen Shot 2018-12-21 at 5.57.49 PM.png](https://images.zenhubusercontent.com/5b523735b69de9433c05431a/5b36194c-e5d4-4ec9-bc17-ef606eeb6360)
@metasoarous the nature of the timepoint multiplicity metric is that they should always have at least one timepoint with multiplicity of at least 1, right?

**Comment by eharkins** [comment]
@metasoarous can you push the changes you made to the build_olmsted_data script to get these data and I can add in a bit that defaults to multiplicity 1 for at least one timepoint?

**Comment by eharkins** [comment]
Some leaves definitely have no timepoint multiplicities
```0:
aa_seq: "DIVMTQSPDSLAVSLGERATINCKSSQSVLYSSNNKNYLAWYQQKPGQPPKLLIYWASTRESGVPDRFSGSGSGTDFTLTISSLQAEDVAVYYCQQYYSTPLTFGGGTKVEIK"
cluster_multiplicity: null
cluster_timepoint_multiplicities: Array(0)
length: 0
__proto__: Array(0)
distance: 0.00305
height: 1
id: "bk-5442-3"
label: "bk-5442-3"
lbi: 0.7054948084978396
lbr: 0
leaf_size_by: 3
length: 0.00299
multiplicity: 3
nt_seq: "GACATCGTGATGACCCAGTCTCCAGACTCCTTGGCTGTGTCTCTGGGCGAGAGGGCCACCATCAACTGCAAGTCCAGCCAGAGTGTTTTATACAGCTCCAACAATAAGAACTACTTAGCTTGGTACCAGCAGAAACCAGGACAGCCTCCTAAGCTGCTCATTTACTGGGCATCTACCCGGGAATCCGGGGTCCCTGACCGATTCAGTGGCAGCGGGTCTGGGACAGATTTCACTCTCACCATCAGCAGCCTGCAGGCTGAAGATGTGGCAGTTTATTACTGTCAGCAATATTATAGTACTCCGCTCACTTTCGGCGGAGGGACCAAGGTGGAGATCAAA"
parent: "88"
timepoint: "p31"
timepoint_multiplicities: [{…}]
type: "leaf"
x: 71.39311535556274
y: 50
```


That one has no cluster_timepoint_multiplicities

**Comment by eharkins** [comment]
This works for now, closing but see #130
