### ISSUE TITLE
Fix table styling

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#72]
Some things broke in a recent commit:

![image](https://user-images.githubusercontent.com/88556/46510170-1f8fbd80-c7fc-11e8-8aa8-7e196b279ff6.png)

In summary:

* selected clonal family row isn't solidly highlighted any more
* select boxes aren't centered any more

I have a feeling this has to do with some style property taken off one of the grid components, based on alignment or something. I'm guessing it's partly complicated because of the changes we made to the way the table spaces itself out.

**Comment by eharkins** [comment]
Your feeling about the style property is right. It seems like for some reason with `place-self` (https://css-tricks.com/snippets/css/complete-guide-grid/#article-header-id-32)  you can't have it centered and stretch to fill the grid-area in both directions (horizontal and vertical). Before we had `place-self: center stretch` which looks like this (just stretches horizontal for some reason): 
![screen shot 2018-10-04 at 6 39 04 pm](https://user-images.githubusercontent.com/12140437/46511681-cb3d0b80-c804-11e8-83dd-141ff3417f20.png)
So I am adding some more margin on the style of the checkbox component to take care of centering it, and using `place-self: stretch` so it will look like this:
![screen shot 2018-10-04 at 6 40 43 pm](https://user-images.githubusercontent.com/12140437/46511729-1bb46900-c805-11e8-83ba-adf4130d1fb8.png)

**Comment by metasoarous** [comment]
OK; This looks pretty decent. Ideally though the other columns would be centered as well though. Maybe set a min-height or fixed height? I hate to hardwire stuff like this, cause ideally it would all just be responsive. And actually, I don't really mind the way its been highlighting things as long as its vertically centered, so I'm not sure it's worth making that sacrifice; I actually think it looks kind of cool. I'm fine with highlighting the entire row as you're aiming to do above, but not over having things aligned consistently.

**Comment by eharkins** [comment]
I agree about the hardwiring comment and the desire for it to be responsive. Regarding having the columns centered - do you mean vertically within their row space (`align-self`) or horizontally within their column space  (`justify-self`) ? For each of these independently, the settings `center` (center with respect to row or column for align-self or justify-self, respectively) and `stretch` (stretch to fill available space in the row or column for align-self or justify-self, respectively) are mutually exclusive. So if we want things to stretch width wise to have no gaps as you were pointing out in the initial picture, it seems like we cant also have them centered within the column (this seems weird to me but its my interpretation of the Grid docs) with just grid settings.

**Comment by eharkins** [comment]
This may be a separate issue (let me know if it's worth creating) but we could also redesign the table to not need the checkboxes. There are other ways to cue people in to so that they could just click on a row (as is done on the splash page) to select a family. I guess we left the checkboxes there in that case because we wanted it to alert users that they should click on rows to select them, but we could use another cue such as making the mouse a hand icon or changing the color of the row on hover.

**Comment by metasoarous** [comment]
Center vertically, do not center horizontally.

**Comment by eharkins** [comment]
Ok we can just do `place-self: center stretch` then since you said you don't mind the highlighting like so:
![screen shot 2018-10-04 at 6 39 04 pm](https://user-images.githubusercontent.com/12140437/46564374-bb343300-c8bb-11e8-9775-2d28afd7cfe9.png)
It looks a little weird to me but I don't mind leaving that for later if it becomes an issue.

**Comment by metasoarous** [comment]
Up to you; Maybe for now go back to the "little weird" style, but open an issue to make it less weird. I kind of wonder if there isn't a css-grid style control for doing this sort of thing differently...

Reclose once you have the "little weird" style merged in.
