### ISSUE TITLE
Add rearrangement plot above alignment

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#73]
Add gene rearrangement plot (like in grid/table naive sequence column) to the top of the alignment view, so you know where the mutations are falling relative to CDR3, etc:

![image](https://user-images.githubusercontent.com/88556/46564017-b3738f00-c8b9-11e8-9f1c-74f1a179f5d5.png)

We already have the code for this in a different context, so it would seem most of the challenge would be in stitching it together with what we have and making sure things align properly.

**Comment by eharkins** [comment]
I wonder if it might be easier to align said plot with the existing alignment if we included it as a part of the existing viz as either one of:
* just another row above naive color coded separately by gene region
* a customized axis at the top of the viz

**Comment by metasoarous** [comment]
Customized axis or grid marks would be cool, and might feel very intuitive. Another row could be great too though.

**Comment by eharkins** [comment]
Discussing with @metasoarous , we know this is simple for annotations we know we already have (CDR3), we aren't positive if we have similar annotations for other CDRs, this could be a separate issue?

**Comment by metasoarous** [comment]
@psathyrella Which CRD region datas do you have in the partis output? Possibility of getting more or easily computing this ourselves?

**Comment by eharkins** [comment]
@metasoarous according to https://github.com/psathyrella/partis/blob/master/docs/output-formats.md it looks like just v, d, j, cdr3 unless @psathyrella has added more since updating that doc.

**Comment by psathyrella** [comment]
@metasoarous @eharkins partis only outputs cdr3 info. This is because it's the only cdr with a really unambiguous definition. There's a longer thread on b-t.cr where folks were discussing this, I could probably dig it up, but the gist is that cdr1 and cdr2 don't have as immutable of a definition, and instead depend on what alignment of the different V genes you want to use. CDR3 is different because most everyone agrees that if you don't have a cyst and tryp/phen where they usually are at start/end of cdr3, it's very uncommon to get a functional BCR.

That said it's fairly easy to get the cdr1/2 info, I just don't want to have it by default, because it requires a specific alignment (probably imgt), which keeps changing, and which you have to decide how to extend for new genes. The quick and dirty way to get alignments is pass [this](https://github.com/psathyrella/partis/blob/dev/data/germlines/imgt-aligned-igh.fa) as the argument to `--aligned-germline-fname` (this is designed to be used for writing presto output, since presto requires imgt alignments). That of course doesn't solve the problem of adding new genes to that alignment file, or deciding if that is the alignment you want... but those issues are why it's not really a supported option.

I could be convinced that cdr1/2 should be added if it helps a lot, but I'm inclined to say it's better if you tack in on afterwards, since it's a property of the germline set, and doesn't have to do with the annotations or partitions (for instance, that ^ aligned file probably has all the info you need, and you'd just need to add a quick alignment for any new V genes).

**Comment by metasoarous** [comment]
Thanks @psathyrella ; I'll defer to @lauradoepker on this, as it was her request. All things being equal, I would love to see CDR1/2 regions annotated. But if it's going to be messy, I'd just as soon kick the can down the road for now. Perhaps for now we open an issue for this in CFT so we can prioritize in relation to everything else separately?

**Comment by eharkins** [comment]
@lauradoepker do we just want CDR3 here as opposed to v, d, j boundaries?

**Comment by eharkins** [comment]
Would this be more useful @metasoarous as opposed to something that isn't visible throughout the viz (such as an axis)?
![Screen Shot 2018-10-29 at 6.15.49 PM.png](https://images.zenhubusercontent.com/5b523735b69de9433c05431a/772d9424-6a8c-4072-a0e9-af5aa71f98d1)

**Comment by metasoarous** [comment]
I'd ideally like to see all of the arrangement info we have, not just the crd3. So v/d/j bounds, non-templated insertions, etc. I'm not sure this approach will translate as well there, and kind of like the idea of reinforcing the meaning by using more or less the same viz as in the table. What do you think @lauradoepker?

**Comment by eharkins** [comment]
Here's what it looks like with that plus the rule included for CDR3
![screen shot 2018-10-30 at 12 00 45 pm](https://user-images.githubusercontent.com/12140437/47743103-780b7c80-dc3b-11e8-88a9-1bcddc8b9f19.png)

**Comment by metasoarous** [comment]
Looks dope! One thing to clean up would be rename "Amino acid color scale" to something shorter like "AA colors" or "AA key" to keep from taking up all that whitespace on the right? I like that you included the scale for the rearrangement map though.

**Comment by eharkins** [comment]
Yeah I can shorten it or move the key to the top as well (thought it would be better to separate from the gene region stuff). It could also go on the bottom just below the "amino acid position" axis. The reason I had originally moved it to the top as opposed to the side was because it's so long and dictates the height of the viz when it would otherwise be small. E.g.
![screen shot 2018-10-30 at 4 16 10 pm](https://user-images.githubusercontent.com/12140437/47756435-47d5d500-dc5f-11e8-9aa0-178754d0426e.png)
But I also thought it looked cluttered when they are both up top e.g.
![screen shot 2018-10-30 at 4 19 08 pm](https://user-images.githubusercontent.com/12140437/47756505-9aaf8c80-dc5f-11e8-865c-343ed05c9856.png)
So I think the best thing is to shorten the label and keep it on the side or put it on the bottom

**Comment by lauradoepker** [comment]
This looks great @eharkins though I'm really interested in CDR1 and CDR2 as well as CDR3.  There aren't so clear of demarcations for these CDRs as for CDR3, so not sure how we'll do this.  I usually find them by eye... which isn't helpful.

**Comment by eharkins** [comment]
@lauradoepker we are tracking that now in https://github.com/matsengrp/cft/issues/254. Once those CDR1 and 2 bounds are available from cft, then we can certainly add them to this part of the viz. Maybe it's worth creating an olmsted issue so we remember to do that?
