### ISSUE TITLE
Fit tree/alignment height by default

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#83]
Should still be possible to resize to be more legible as necessary. Either by dragging slider or container boundary, or by clicking an "expand" button that gives labels a fixed amount of breathing room.

**Comment by eharkins** [comment]
@metasoarous Is this in the context of having the tree / alignment slider #59 ? I know we talked about this today but I'm slightly unclear on where we landed with the priority for now in terms of sizing the height of the tree. Are you just saying here it should fit onto the screen by default (set the height scale according to screen height when it renders) but then allow you to still control the height scale?

**Comment by metasoarous** [comment]
That is what I'm saying, yes, and I believe that's what we agreed on for now.

**Comment by eharkins** [comment]
@metasoarous I wonder if it would be better to size the tree initially according to its breadth. Sizing it to fit the screen might look odd if you have a lot of screen real estate and a very small tree like this:
![screen shot 2018-10-17 at 10 43 49 am](https://user-images.githubusercontent.com/12140437/47105724-9adc7080-d1f9-11e8-8ab9-76d50d9e16bc.png)
This isn't so bad since at least everything is clearly visible but this isn't the case if you don't have much screen height to work with but you have a large tree:
![screen shot 2018-10-17 at 10 44 52 am](https://user-images.githubusercontent.com/12140437/47105811-ce1eff80-d1f9-11e8-9657-71c8d631138e.png)
I'm suggesting that we continue to size it according to the number of leaves (breadth), but I'm still thinking about this and open to other ideas or a reason we should prioritize fitting to screen height

**Comment by eharkins** [comment]
>Regarding the first issue, we should perhaps add some computation that sets a max branch scale according to the max expected size for a pie chart. That would resolve the problem nicely.

Do you mean max height scale or branch scale? Setting the max value for the range input I think must be a number, I've been having trouble setting it to a signal value. But if I understand you correctly, we want to set the maximum height of the tree relative to the maximum possible size of a pie chart so that they don't overlap but also don't get spread out too much as in my first screenshot above? Is the desired result something like this (with leaf size and height at their max values)?:
![screen shot 2018-10-22 at 11 39 34 am](https://user-images.githubusercontent.com/12140437/47312021-15d5ca80-d5f0-11e8-9488-f64abfb7585d.png)

If so, we could just use a JS variable for this (to avoid hardcoding in multiple places) since this value wouldn't need to update with the current value of the tree height scale.

>For the latter issue though, I'd rather see the fontsize of the labels decrease so they don't overlap each other. Or hell, remove them entirely unless they're being hovered on (if below a certain branch scale threshold perhaps). I'd rather (by default) see the whole tree than be able to clearly read all the stupid node names. As long as folks can still zoom in (#64) to see these details, we should be fine.

Makes sense to me, I'll try out both options. We could have a radio button for `display node names` as some tree viewers do; this might be more practical for being able to see all of them at once or not at all as apposed to hover, e.g. if user wants to remember where in the tree the selected sequence is then they don't have to hover over many in search of it.

**Comment by metasoarous** [comment]
@eharkins Your thoughts on a fixed max make sense; because we have a default max size for the pie charts, we can just calculate a fixed value based on that; should be good enough for government work.

Like the idea of also having a display name toggle; sounds good.

**Comment by eharkins** [comment]
We have a solution to this now at the expense of having pie charts from #56 size initially according to the height of the viz. For now I think this is worth it, so I have set a reasonable default for the max pie chart size and can also open an issue to fix this once [vega allows initializing values for signals bound to selections](https://github.com/vega/vega-lite/pull/4139#issuecomment-434898399). We could also do something similar to what we have done for the height (as an intermediate solution), which is to make the slider set some scaling factor - by which the the signal for the pie chart size is multiplied. Then the pie charts could update with the viz height and if you want to double their scale, you can set the slider to 2 instead of 1. @metasoarous let me know if this needs clarification in any way.

**Comment by metasoarous** [comment]
Looks good! And honestly, even when the pies overlap quite a bit, the transparency actually does a surprisingly good job of making things look sane. So that's great.

One qualm here is it might be nice to have a little more vertical padding. It feels a little cramped and hard to get in the window. Fine for now, but maybe if we think about it we can tweak this a bit in final styling pass.
