### ISSUE TITLE
Client side caching of clonal families data

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#97]
For a brief moment we noted on one of our browsers yesterday that the clonal families data wasn't even getting fetched, because it had been cached client side. However, we've been unable to replicate this. If we had the browser consistently caching these payloads, loading the app would be much faster for clients which had already loaded the data. It's _possible_ that it's not caching because the data payloads are just too big, but this has to be explored further.

**Comment by eharkins** [comment]
I think the reason we haven't been able to replicate this is because the reason it happened that one time is that the initial request had failed, making the resource small enough to be cached since it transferred some bytes but not the majority of the file. This would explain why `clonal_families.json` doesn't seem to get cached in the above commit. I can't confirm for certain that the reason it doesn't cache is because the actual size of the file (45 MB or so) is too large to be cached on the client, but that seems like the main difference between the requests for `clonal_families.json` and `datasets.json`. I didn't find much useful information when searching for a way to verify that a file is too large for the cache; I tried looking at chrome://net-internals/#events but it just basically says that the cache entry failed for that file:
![screen shot 2018-11-09 at 1 13 30 pm](https://user-images.githubusercontent.com/12140437/48288598-87e84500-e421-11e8-87f1-9be9017e13c1.png)

 I think in general having `clonal_families.json` contain all clonal families for all datasets is making life difficult in general for requesting clonal families data with reasonable performance.

**Comment by eharkins** [comment]
We are now separating the files by dataset and requesting them on a by-dataset basis, as well as zipping them for faster transfer over the network. This also happens to allow the files to be cached on the client (for me when I have tried) but of course this is dependent on the client and their available cache space. So this is not necessarily something we can ever guarantee

**Comment by eharkins** [comment]
We also should close #61 unless we think there will be more work to do in the future re: zipping
